In [19]:
import pandas
import numpy as np

In [20]:
pandas.__version__

'1.1.1'

In [21]:
mylist=[1,2,4]

In [22]:
mylist

[1, 2, 4]

In [23]:
myarr=np.array(mylist)

In [24]:
type(myarr)

numpy.ndarray

In [25]:
mymatrix=[[1,2,3],[6,7,8],[11,12,13]]

In [26]:
mymatrix

[[1, 2, 3], [6, 7, 8], [11, 12, 13]]

In [27]:
np.array(mymatrix)

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [28]:
arr=np.arange(0,25)

In [29]:
arr.reshape(6,6)

ValueError: cannot reshape array of size 25 into shape (6,6)

In [30]:
ranarr=np.random.randint(0,101,10)

In [31]:
ranarr

array([ 8, 65, 10, 68, 55, 56,  5, 76, 43,  8])

In [32]:
myarray=np.linspace(0,10,101)

In [33]:
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [38]:
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

In [39]:
account_total =  np.sum(account_transactions)


In [40]:
account_total

2720

In [43]:
account_total2 =  account_transactions.sum()

In [44]:
account_total2

2720

In [82]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [101]:
total_two_bool=[dice_rolls>2]

In [104]:
total_rolls_over_two = len(dice_rolls[total_two_bool])

c:\users\thorugo\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


In [105]:
total_rolls_over_two

19